#-------------------------------------------------------------------
# Description
#-------------------------------------------------------------------
## This workflow runs the T1D_analysis code on the S3it cluster.
## The dataset contains 2 panels, which are defined via wildcards. 
## Hence, preprocessing of the 2 panels occurs in parallel. 

# Scope:
## Start: Extraction of features after segmentation. 
## Body: Import, Spillover Compensation, Transformation, QC,
## End: Cell-Type Annotation.
## Not convered: downstream analysis.

#--------------------------------------------------------------------
# Parameters
#--------------------------------------------------------------------
configfile: "workflow/config.yaml"
home_dir = config["home_dir"]
data_dir = config["data_dir"]
container_path = config["container_dir"]

#-------------------------------------------------------------------
# Container
#-------------------------------------------------------------------
container: container_path

#-------------------------------------------------------------------
# Output
#-------------------------------------------------------------------
## Snakemake: Figure out how to generate these 2 files.
rule targets:
    input: 
        home_dir + "docs/08_CellTypesNonImmune_cells_Immune.html", # Immune Panel
        home_dir + "docs/08_CellTypesNonIslet_cells_Islet.html" # Islet Panel.

#-------------------------------------------------------------------
# R-Scripts
#-------------------------------------------------------------------
## Define Analysis Rules.
#-------------------------------------------------------------------
## 1) Import of pre-processed data.
rule ImportData_cells_01_r:
    input:
        script=home_dir + "analysis/01_ImportData_cells_{panel}.Rmd",
        prev_out=data_dir + "processing/txt_output/05_ImageRegistration.out"
    output:
        home_dir + "docs/01_ImportData_cells_{panel}.html",
    benchmark:
        home_dir + "benchmark/01_ImportData_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=170000,
        time="5:00:00"
    script:
        home_dir + "analysis/01_ImportData_cells_{wildcards.panel}.Rmd"

#-------------------------------------------------------------------
## 2) Spillover-Compensation.
rule SpilloverCompensation_cells_02_r:
    input:
        script=home_dir + "analysis/02_SpilloverCompensation_cells_{panel}.Rmd",
        prev_out=home_dir + "docs/01_ImportData_cells_{panel}.html"
    output:
        home_dir + "docs/02_SpilloverCompensation_cells_{panel}.html",
    benchmark:
        home_dir + "benchmark/02_SpilloverCompensation_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=80000, #80GB,
        time="5:00:00"
    script:
        home_dir + "analysis/02_SpilloverCompensation_cells_{wildcards.panel}.Rmd"

#-------------------------------------------------------------------
## 3) Batch Correction.
rule TransformCorrect_cells_03_r:
    input:
        script=home_dir + "analysis/03_TransformCorrect_cells_{panel}.Rmd",
        prev_out=home_dir + "docs/02_SpilloverCompensation_cells_{panel}.html",
    output:
        home_dir + "docs/03_TransformCorrect_cells_{panel}.html"
    benchmark:
        home_dir + "benchmark/03_TransformCorrect_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=376000, #376Gb
        time="36:00:00"
    script:
        home_dir + "analysis/03_TransformCorrect_cells_{wildcards.panel}.Rmd"

#-------------------------------------------------------------------
## 4) QC of Images
rule QualityControl_cells_04_r:
    input:
        script=home_dir + "analysis/04_QualityControl_cells_{panel}.Rmd",
        prev_out=home_dir + "docs/03_TransformCorrect_cells_{panel}.html",
    output:
        html = home_dir + "docs/04_QualityControl_cells_{panel}.html",
    benchmark:
        home_dir + "benchmark/04_QualityControl_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=376000, #247GB
        time="96:00:00"
    #script:
    #    home_dir + "analysis/04_QualityControl_cells_{wildcards.panel}.Rmd"
    shell:
        """
        Rscript --vanilla -e '
            rmarkdown::render(
                input = "{input.script}",
                output_file = "{output.html}",
                quiet = FALSE,
                knit_root_dir = "{home_dir}analysis",
                params = list(rmd="{input.script}")
            )'
        """

#-------------------------------------------------------------------
## 5) Annotate Cell Types Hierarchy Level 1.
rule CellCategories_cells_05_r:
    input:
        script=home_dir + "analysis/05_CellCategories_cells_{panel}.Rmd",
        prev_out=home_dir + "docs/04_QualityControl_cells_{panel}.html",
    output:
        home_dir + "docs/05_CellCategories_cells_{panel}.html",
    benchmark:
        home_dir + "benchmark/05_CellCategories_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=350000, #350Gb
        time="24:00:00"
    script:
        home_dir + "analysis/05_CellCategories_cells_{wildcards.panel}.Rmd"

#-------------------------------------------------------------------
## 6) Annotate Cell Types Hierarchy Level 2.
rule CellCategories_cells_06_r:
    input:
        script=home_dir + "analysis/06_CellTypes{panel}_cells_{panel}.Rmd",
        prev_out=home_dir + "docs/05_CellCategories_cells_{panel}.html",
    output:
        home_dir + "docs/06_CellTypes{panel}_cells_{panel}.html",
    benchmark:
        home_dir + "benchmark/06_CellTypes{panel}_cells_{panel}.txt"
    threads: 8
    resources:
        mem_mb=247000, #350Gb
        time="24:00:00"
    script:
        home_dir + "analysis/06_CellTypes{panel}_cells_{wildcards.panel}.Rmd"
#-------------------------------------------------------------------
## 7) Cell Type Annotation; hierarchy 3. 
## Immune panel only.
rule CellCategories_cells_07_r:
    input:
        script= home_dir + "analysis/07_ClustersImmune_cells_Immune.Rmd",
        prev_out= home_dir + "docs/06_CellTypesImmune_cells_Immune.html",
    output:
        home_dir + "docs/07_ClustersImmune_cells_Immune.html",
    benchmark:
        home_dir + "benchmark/07_ClustersImmune_cells_Immune.txt"
    threads: 48
    resources:
        mem_mb=247000, #350Gb
        time="24:00:00"
    script:
        home_dir + "analysis/07_ClustersImmune_cells_Immune.Rmd"

#-------------------------------------------------------------------
## 8a) Cell Type Annotation; hierarchy 4. 
## Islet panel only. Input 06.
rule CellCategories_cells_08_Islet_r:
    input:
        script= home_dir + "analysis/08_CellTypesNonIslet_cells_Islet.Rmd",
        prev_out= home_dir + "docs/06_CellTypesIslet_cells_Islet.html",
    output:
        home_dir + "docs/08_CellTypesNonIslet_cells_Islet.html",
    benchmark:
        home_dir + "benchmark/08_CellTypesNonIslet_cells_Islet.txt"
    threads: 48
    resources:
        mem_mb=247000, #350Gb
        time="24:00:00"
    script:
        home_dir + "analysis/08_CellTypesNonIslet_cells_Islet.Rmd"

#-------------------------------------------------------------------
## 8b) Cell Type Annotation; hierarchy 4. 
## Immune panel only. Input 07.
rule CellCategories_cells_08_Immune_r:
    input:
        script= home_dir + "analysis/08_CellTypesNonImmune_cells_Immune.Rmd",
        prev_out= home_dir + "docs/07_ClustersImmune_cells_Immune.html",
    output:
        home_dir + "docs/08_CellTypesNonImmune_cells_Immune.html",
    benchmark:
        home_dir + "benchmark/08_CellTypesNonImmune_cells_Immune.txt"
    threads: 48
    resources:
        mem_mb=247000, #350Gb
        time="24:00:00"
    script:
        home_dir + "analysis/08_CellTypesNonImmune_cells_Immune.Rmd"

# Add next scripts here for reproducibility. 

#---------------------------------------------------------------------------
# Python-scripts (Preprocessing)
#---------------------------------------------------------------------------
## Local paths in input and output; Container paths for script.
#---------------------------------------------------------------------------
## 05) Image Registration.
rule Registration_05_py:
    input:
        data_dir + "T1D_preprocessing/processing/05_ImageRegistration.py",
        data_dir + "processing/txt_output/04_Measurements.out",
    output:
        data_dir + "processing/txt_output/05_ImageRegistration.out"
    threads: 8
    resources:
        mem_mb=64000, # 64GB
        time="3:00:00"
    script: data_dir + "T1D_preprocessing/processing/05_ImageRegistration.py"

#---------------------------------------------------------------------------
## 04) Feature Extraction.
rule Measurements_04_py:
    input:
        data_dir + "T1D_preprocessing/processing/04_Measurements.py",
        data_dir + "processing/txt_output/03_CellSegmentation.out"
    output: 
        data_dir + "processing/txt_output/04_Measurements.out"
    threads: 8
    resources:
        mem_mb=120000, # 120GB
        time="24:00:00"
    script: data_dir + "T1D_preprocessing/processing/04_Measurements.py"

#---------------------------------------------------------------------------
## 03) Cell Segmentation.
rule CellSegmentation_03_py:
    input:
        data_dir + "T1D_preprocessing/processing/03_CellSegmentation.py",
        data_dir + "processing/txt_output/02_IsletSegmentation.out"
    output: 
        data_dir + "processing/txt_output/03_CellSegmentation.out"
    threads: 8
    resources:
        mem_mb=120000, # 120GB
        time="24:00:00"
    script: data_dir + "T1D_preprocessing/processing/03_CellSegmentation.py"

#---------------------------------------------------------------------------
## 02) Islet Segmentation.
rule IsletSegmentation_02_py:
    input:
        data_dir + "T1D_preprocessing/processing/02_IsletSegmentation.py",
        data_dir + "processing/txt_output/01_Preprocessing.out"
    output: 
        data_dir + "processing/txt_output/02_IsletSegmentation.out"
    threads: 8
    resources:
        mem_mb=120000, # 120GB
        time="24:00:00"
    script: data_dir + "T1D_preprocessing/processing/02_IsletSegmentation.py"

#---------------------------------------------------------------------------
## 01) Feature Extraction.
rule Preprocessing_01_py:
    input:
        data_dir + "T1D_preprocessing/processing/01_Preprocessing.py",
        data_dir + "T1D_preprocessing/processing/helper_functions.py"
    output: 
        data_dir + "processing/txt_output/01_Preprocessing.out"
    threads: 8
    resources:
        mem_mb=120000, # 120GB
        time="24:00:00"
    script: data_dir + "T1D_preprocessing/processing/01_Preprocessing.py"
